<a href="https://colab.research.google.com/github/joluva/datascience/blob/main/CNDS_MOD_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importamos las librerias necesarias pandas y numpy
import pandas as pd
import numpy as np
import os

#os.chdir("C:/TeclaLab/DataScience/VisualizacionYTableau/MOD-2/Python/")

In [ ]:
# importamos los archivos originales .CSV con los que trabajaremos
# datos macroeconomicos (PBI, inflacion, deuda, resultado comercial y fiscal)
macro = pd.read_csv("datos_macro.csv")

# tipos de cambios de brasil y de argentina(valor del dolar en reales y pesos argentina)
tc_br = pd.read_csv("tc_brasil.csv")
tc_ar = pd.read_csv("tc_argentina.csv")

In [ ]:
# importamos nuevamente el archivo pero sin las ultimas 3 filas
macro = pd.read_csv('datos_macro.csv', skipfooter=3, engine='python')

# filtramos las observaciones/filas que correspondan los paises y variables que queremos
macro_f = macro[(macro["Country"].isin(["Argentina","Chile","Brazil"])) &
                (macro["Subject Descriptor"] == "Gross domestic product, constant prices") &
                (macro["Units"] == "Percent change")]

macro_f

,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,...,2018,2019,2020,2021,2022,2023,2024,2025,2026,Estimates Start After
271,213,ARG,NGDP_RPCH,Argentina,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,NaN,"See notes for: Gross domestic product, consta...",0.7,...,-2.565,-2.088,-9.905,7.5,2.465,2,1.799,1.751,1.836,2020.0
1081,223,BRA,NGDP_RPCH,Brazil,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,NaN,"See notes for: Gross domestic product, consta...",9.19,...,1.784,1.411,-4.059,5.229,1.522,2.014,2.102,2.117,2.129,2020.0
1576,228,CHL,NGDP_RPCH,Chile,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,NaN,"See notes for: Gross domestic product, consta...",7.945,...,3.718,1.015,-5.845,10.999,2.471,1.878,1.99,2.273,2.49,2020.0

In [ ]:
# eliminamos las columnas que ya no necesitamos
macro_f = macro_f.drop(columns = ["WEO Country Code", "ISO", "WEO Subject Code", "Subject Descriptor",
                                  "Subject Notes", "Units", "Scale", "Country/Series-specific Notes",
                                  "Estimates Start After"])
macro_f

,Country,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
271,Argentina,0.7,-5.744,-3.149,3.733,2,-6.951,7.146,2.529,-1.957,...,2.819,-2.565,-2.088,-9.905,7.5,2.465,2,1.799,1.751,1.836
1081,Brazil,9.19,-4.4,0.596,-3.4,5.307,7.901,7.544,3.601,0.264,...,1.323,1.784,1.411,-4.059,5.229,1.522,2.014,2.102,2.117,2.129
1576,Chile,7.945,6.212,-13.588,-2.802,5.886,1.968,5.596,6.581,7.288,...,1.154,3.718,1.015,-5.845,10.999,2.471,1.878,1.99,2.273,2.49

In [ ]:
# transponemos la tabla para tenerla en formato largo, dejando fijo el pais
# convirtiendo los años de columnas a filas, y definiendo la variable de valores como crecimiento_pbi
macro_tr = pd.melt(macro_f, id_vars = ["Country"], var_name="year", value_name="crecimiento_pbi")
macro_tr

       Country  year crecimiento_pbi
0    Argentina  1980             0.7
1       Brazil  1980            9.19
2        Chile  1980           7.945
3    Argentina  1981          -5.744
4       Brazil  1981            -4.4
..         ...   ...             ...
136     Brazil  2025           2.117
137      Chile  2025           2.273
138  Argentina  2026           1.836
139     Brazil  2026           2.129
140      Chile  2026            2.49

[141 rows x 3 columns]

In [ ]:
# cambiamos el nombre de country por pais
macro_tr = macro_tr.rename(columns = {"Country":"pais"})

macro_tr

          pais  year crecimiento_pbi
0    Argentina  1980             0.7
1       Brazil  1980            9.19
2        Chile  1980           7.945
3    Argentina  1981          -5.744
4       Brazil  1981            -4.4
..         ...   ...             ...
136     Brazil  2025           2.117
137      Chile  2025           2.273
138  Argentina  2026           1.836
139     Brazil  2026           2.129
140      Chile  2026            2.49

[141 rows x 3 columns]

In [ ]:
# ordenamos la tabla por pais y por año
macro_tr = macro_tr.sort_values(by = ["pais","year"])
macro_tr

          pais  year crecimiento_pbi
0    Argentina  1980             0.7
3    Argentina  1981          -5.744
6    Argentina  1982          -3.149
9    Argentina  1983           3.733
12   Argentina  1984               2
..         ...   ...             ...
128      Chile  2022           2.471
131      Chile  2023           1.878
134      Chile  2024            1.99
137      Chile  2025           2.273
140      Chile  2026            2.49

[141 rows x 3 columns]

In [ ]:
# tipos de variables
macro_tr.dtypes

pais               object
year               object
crecimiento_pbi    object
dtype: object

In [ ]:
macro_tr

          pais  year crecimiento_pbi
0    Argentina  1980             0.7
3    Argentina  1981          -5.744
6    Argentina  1982          -3.149
9    Argentina  1983           3.733
12   Argentina  1984               2
..         ...   ...             ...
128      Chile  2022           2.471
131      Chile  2023           1.878
134      Chile  2024            1.99
137      Chile  2025           2.273
140      Chile  2026            2.49

[141 rows x 3 columns]

In [ ]:
# convertimos algunos de los campos a tipos de variables que nos sirvan: años como enteros, credimiento como float
macro_tr = macro_tr.astype({"pais": str, "year": int, "crecimiento_pbi": float})
macro_tr.dtypes

pais                object
year                 int64
crecimiento_pbi    float64
dtype: object

In [ ]:
# filtramos las observaciones anteriores a 2020, el ultimo año con datos completos
macro_tr = macro_tr[macro_tr["year"]<=2020]
macro_tr

          pais  year  crecimiento_pbi
0    Argentina  1980            0.700
3    Argentina  1981           -5.744
6    Argentina  1982           -3.149
9    Argentina  1983            3.733
12   Argentina  1984            2.000
..         ...   ...              ...
110      Chile  2016            1.725
113      Chile  2017            1.154
116      Chile  2018            3.718
119      Chile  2019            1.015
122      Chile  2020           -5.845

[123 rows x 3 columns]

In [ ]:
# calculamos las principales estadisticas descriptivas de la variable crecimiento
macro_tr['crecimiento_pbi'].describe()

count    123.000000
mean       2.613829
std        4.774905
min      -13.588000
25%        0.069000
50%        3.301000
75%        5.945000
max       11.132000
Name: crecimiento_pbi, dtype: float64

In [ ]:
# concatenamos las tablas con el tipo de cambio de brasil y argentina
tc = pd.concat([tc_br, tc_ar])
tc

         pais  year  tipo_de_cambio
0      Brasil  1994      537.595539
1      Brasil  1995        0.916098
2      Brasil  1996        1.004129
3      Brasil  1997        1.077567
4      Brasil  1998        1.159965
5      Brasil  1999        1.812446
6      Brasil  2000        1.827904
7      Brasil  2001        2.347382
8      Brasil  2002        2.933334
9      Brasil  2003        3.066170
10     Brasil  2004        2.926529
11     Brasil  2005        2.454571
12     Brasil  2006        2.177439
13     Brasil  2007        1.949748
14     Brasil  2008        1.807751
15     Brasil  2009        1.987381
16     Brasil  2010        1.761073
17     Brasil  2011        1.669337
18     Brasil  2012        1.951801
19     Brasil  2013        2.155172
20     Brasil  2014        2.350627
21     Brasil  2015        3.336004
22     Brasil  2016        3.487878
23     Brasil  2017        3.190050
24     Brasil  2018        3.650044
25     Brasil  2019        3.942021
26     Brasil  2020        5.160210
27     Brasil  2021        5.378064
0   Argentina  1990             NaN
1   Argentina  1991             NaN
2   Argentina  1992             NaN
3   Argentina  1993             NaN
4   Argentina  1994        1.000000
5   Argentina  1995        1.000000
6   Argentina  1996        1.000000
7   Argentina  1997        1.000000
8   Argentina  1998        1.000000
9   Argentina  1999        1.000000
10  Argentina  2000        1.000000
11  Argentina  2001        1.010000
12  Argentina  2002        3.242500
13  Argentina  2003        2.949324
14  Argentina  2004        2.942366
15  Argentina  2005        2.923175
16  Argentina  2006        3.074122
17  Argentina  2007        3.115619
18  Argentina  2008        3.161408
19  Argentina  2009        3.730141
20  Argentina  2010        3.912689
21  Argentina  2011        4.130226
22  Argentina  2012        4.551482
23  Argentina  2013        5.478893
24  Argentina  2014        8.118816
25  Argentina  2015        9.268934
26  Argentina  2016       14.779439
27  Argentina  2017       16.566548
28  Argentina  2018       28.093719
29  Argentina  2019       48.242307
30  Argentina  2020       70.594146

In [ ]:
# agregamos por pais, usando el promedio ( promedio de la tasa de crecimiento de pbi)
macro_ag = macro_tr.groupby(["pais"], as_index=False).agg({"crecimiento_pbi":"mean"})
macro_ag

        pais  crecimiento_pbi
0  Argentina         1.556683
1     Brazil         2.232390
2      Chile         4.052415

In [ ]:
# agregacion con numpy
np.max(macro_tr["crecimiento_pbi"])

11.132

In [ ]:
# contamos la cantidad de valores faltantes en tipo de cambio

tc["tipo_de_cambio"].isnull().sum()

np.int64(4)

In [ ]:
# eliminamos las filas en las que aparezca al menos unmissing
tc_ar = tc_ar.dropna(how='any')
tc_br

      pais  year  tipo_de_cambio
0   Brasil  1994      537.595539
1   Brasil  1995        0.916098
2   Brasil  1996        1.004129
3   Brasil  1997        1.077567
4   Brasil  1998        1.159965
5   Brasil  1999        1.812446
6   Brasil  2000        1.827904
7   Brasil  2001        2.347382
8   Brasil  2002        2.933334
9   Brasil  2003        3.066170
10  Brasil  2004        2.926529
11  Brasil  2005        2.454571
12  Brasil  2006        2.177439
13  Brasil  2007        1.949748
14  Brasil  2008        1.807751
15  Brasil  2009        1.987381
16  Brasil  2010        1.761073
17  Brasil  2011        1.669337
18  Brasil  2012        1.951801
19  Brasil  2013        2.155172
20  Brasil  2014        2.350627
21  Brasil  2015        3.336004
22  Brasil  2016        3.487878
23  Brasil  2017        3.190050
24  Brasil  2018        3.650044
25  Brasil  2019        3.942021
26  Brasil  2020        5.160210
27  Brasil  2021        5.378064

In [ ]:
# eliminamos las filas en las que haya missing en la variable tipo_de_cambio
tc_ar = tc_ar.dropna(subset=["tipo_de_cambio"])
tc_ar

         pais  year  tipo_de_cambio
4   Argentina  1994        1.000000
5   Argentina  1995        1.000000
6   Argentina  1996        1.000000
7   Argentina  1997        1.000000
8   Argentina  1998        1.000000
9   Argentina  1999        1.000000
10  Argentina  2000        1.000000
11  Argentina  2001        1.010000
12  Argentina  2002        3.242500
13  Argentina  2003        2.949324
14  Argentina  2004        2.942366
15  Argentina  2005        2.923175
16  Argentina  2006        3.074122
17  Argentina  2007        3.115619
18  Argentina  2008        3.161408
19  Argentina  2009        3.730141
20  Argentina  2010        3.912689
21  Argentina  2011        4.130226
22  Argentina  2012        4.551482
23  Argentina  2013        5.478893
24  Argentina  2014        8.118816
25  Argentina  2015        9.268934
26  Argentina  2016       14.779439
27  Argentina  2017       16.566548
28  Argentina  2018       28.093719
29  Argentina  2019       48.242307
30  Argentina  2020       70.594146

In [ ]:
# analizamos los valores unicos de la variable pais en la tabla marco_tr
macro_tr["pais"].unique()

array(['Argentina', 'Brazil', 'Chile'], dtype=object)

In [ ]:
# inconsistencia en la variable de testo
# en este caso reeplazamos Brasil (español), por Brazil (ingles)
tc_br['pais'] = np.where(tc_br['pais'] == 'Brasil', 'Brazil', tc_br['pais'])
tc_br

      pais  year  tipo_de_cambio
0   Brazil  1994      537.595539
1   Brazil  1995        0.916098
2   Brazil  1996        1.004129
3   Brazil  1997        1.077567
4   Brazil  1998        1.159965
5   Brazil  1999        1.812446
6   Brazil  2000        1.827904
7   Brazil  2001        2.347382
8   Brazil  2002        2.933334
9   Brazil  2003        3.066170
10  Brazil  2004        2.926529
11  Brazil  2005        2.454571
12  Brazil  2006        2.177439
13  Brazil  2007        1.949748
14  Brazil  2008        1.807751
15  Brazil  2009        1.987381
16  Brazil  2010        1.761073
17  Brazil  2011        1.669337
18  Brazil  2012        1.951801
19  Brazil  2013        2.155172
20  Brazil  2014        2.350627
21  Brazil  2015        3.336004
22  Brazil  2016        3.487878
23  Brazil  2017        3.190050
24  Brazil  2018        3.650044
25  Brazil  2019        3.942021
26  Brazil  2020        5.160210
27  Brazil  2021        5.378064

In [ ]:
# identificamos outliers (casos aparte)
tc_br["tc_estandarizado"] = (tc_br["tipo_de_cambio"] - np.mean(tc_br["tipo_de_cambio"]))/np.std(tc_br["tipo_de_cambio"])
tc_br

      pais  year  tipo_de_cambio  tc_estandarizado
0   Brazil  1994      537.595539          5.195833
1   Brazil  1995        0.916098         -0.208381
2   Brazil  1996        1.004129         -0.207494
3   Brazil  1997        1.077567         -0.206755
4   Brazil  1998        1.159965         -0.205925
5   Brazil  1999        1.812446         -0.199355
6   Brazil  2000        1.827904         -0.199199
7   Brazil  2001        2.347382         -0.193968
8   Brazil  2002        2.933334         -0.188068
9   Brazil  2003        3.066170         -0.186730
10  Brazil  2004        2.926529         -0.188136
11  Brazil  2005        2.454571         -0.192889
12  Brazil  2006        2.177439         -0.195679
13  Brazil  2007        1.949748         -0.197972
14  Brazil  2008        1.807751         -0.199402
15  Brazil  2009        1.987381         -0.197593
16  Brazil  2010        1.761073         -0.199872
17  Brazil  2011        1.669337         -0.200796
18  Brazil  2012        1.951801         -0.197951
19  Brazil  2013        2.155172         -0.195903
20  Brazil  2014        2.350627         -0.193935
21  Brazil  2015        3.336004         -0.184013
22  Brazil  2016        3.487878         -0.182483
23  Brazil  2017        3.190050         -0.185482
24  Brazil  2018        3.650044         -0.180850
25  Brazil  2019        3.942021         -0.177910
26  Brazil  2020        5.160210         -0.165643
27  Brazil  2021        5.378064         -0.163450

In [ ]:
# conservamos solo los cambios desde 1995
tc_br2 = tc_br[tc_br["year"]>=1995]
tc_br2

      pais  year  tipo_de_cambio  tc_estandarizado
1   Brazil  1995        0.916098         -0.208381
2   Brazil  1996        1.004129         -0.207494
3   Brazil  1997        1.077567         -0.206755
4   Brazil  1998        1.159965         -0.205925
5   Brazil  1999        1.812446         -0.199355
6   Brazil  2000        1.827904         -0.199199
7   Brazil  2001        2.347382         -0.193968
8   Brazil  2002        2.933334         -0.188068
9   Brazil  2003        3.066170         -0.186730
10  Brazil  2004        2.926529         -0.188136
11  Brazil  2005        2.454571         -0.192889
12  Brazil  2006        2.177439         -0.195679
13  Brazil  2007        1.949748         -0.197972
14  Brazil  2008        1.807751         -0.199402
15  Brazil  2009        1.987381         -0.197593
16  Brazil  2010        1.761073         -0.199872
17  Brazil  2011        1.669337         -0.200796
18  Brazil  2012        1.951801         -0.197951
19  Brazil  2013        2.155172         -0.195903
20  Brazil  2014        2.350627         -0.193935
21  Brazil  2015        3.336004         -0.184013
22  Brazil  2016        3.487878         -0.182483
23  Brazil  2017        3.190050         -0.185482
24  Brazil  2018        3.650044         -0.180850
25  Brazil  2019        3.942021         -0.177910
26  Brazil  2020        5.160210         -0.165643
27  Brazil  2021        5.378064         -0.163450

In [ ]:
# percentil 99 de los valores de tipo de cambio
p99 = np.percentile(tc_br2["tipo_de_cambio"],99)
p99

np.float64(5.3214218213399995)

In [ ]:
# vemos las observaciones por encima del percentil 99
tc_br[tc_br["tipo_de_cambio"]>p99]

      pais  year  tipo_de_cambio  tc_estandarizado
0   Brazil  1994      537.595539          5.195833
27  Brazil  2021        5.378064         -0.163450